
apiVersion: v1
kind: ConfigMap
metadata:
  name: version-config
  namespace: hypercloud5-system
data:
  version.config: |
    modules:
    - name: Kubernetes
      namespace:
      selector:
        matchLabels:
          statusLabel:
          - component=kube-apiserver
          versionLabel:
          - component=kube-apiserver
      readinessProbe:
      versionProbe:
    - name: HyperCloud API Server
      namespace: hypercloud5-system
      selector:
        matchLabels:
          statusLabel:
          - hypercloud5=api-server
          versionLabel:
          - hypercloud5=api-server
      readinessProbe:
      versionProbe:
    - name: HyperCloud Single Operator
      namespace: hypercloud5-system
      selector:
        matchLabels:
          statusLabel:
          - hypercloud=single-operator
          versionLabel:
          - hypercloud=single-operator
      readinessProbe:
      versionProbe:
        container: manager
    - name: HyperCloud Multi Operator
      namespace: hypercloud5-system
      selector:
        matchLabels:
          statusLabel:
          - hypercloud=multi-operator
          versionLabel:
          - hypercloud=multi-operator
      readinessProbe:
      versionProbe:
        container: manager
    - name: HyperCloud Console
      namespace: api-gateway-system
      selector:
        matchLabels:
          statusLabel:
          - app.kubernetes.io/name=console
          versionLabel:
          - app.kubernetes.io/name=console
      readinessProbe:
      versionProbe:
       container: console
    - name: HyperAuth
      namespace:
      selector:
        matchLabels:
          statusLabel:
          versionLabel:
      readinessProbe:
        httpGet:
          path: "https://{{ .Values.global.hyperAuth.url }}/auth/realms/tmax"
    - name: Calico
      namespace: kube-system
      selector:
        matchLabels:
          statusLabel:
          - k8s-app=calico-node
          versionLabel:
          - k8s-app=calico-node
      readinessProbe:
      versionProbe:
    - name: API gateway
      namespace: api-gateway-system
      selector:
        matchLabels:
          statusLabel:
          - app.kubernetes.io/name=traefik
          versionLabel:
          - app.kubernetes.io/name=traefik
      readinessProbe:
      versionProbe:
        container: gateway
    - name: Prometheus
      namespace: monitoring
      selector:
        matchLabels:
          statusLabel:
          - app=prometheus
          versionLabel:
          - app=prometheus
      readinessProbe:
        httpGet:
          path: /-/ready
          port: 9090
          scheme: HTTP
      versionProbe:
        container: prometheus
    - name: Tekton
      namespace: tekton-pipelines
      selector:
        matchLabels:
          statusLabel:
          - app=tekton-pipelines-controller
          versionLabel:
          - app=tekton-pipelines-controller
      readinessProbe:
      versionProbe:
    - name: CAPI
      namespace: capi-system
      selector:
        matchLabels:
          statusLabel:
          - cluster.x-k8s.io/provider=cluster-api
          versionLabel:
          - cluster.x-k8s.io/provider=cluster-api
      readinessProbe:
      versionProbe:
        container: manager
    - name: Grafana
      namespace: monitoring
      selector:
        matchLabels:
          statusLabel:
          - app=grafana
          versionLabel:
          - app=grafana
      readinessProbe:
        httpGet:
          path: /api/health
          port: 3000
      versionProbe:
    - name: ArgoCD
      namespace: argocd
      selector:
        matchLabels:
          statusLabel:
          - app.kubernetes.io/name=argocd-server
          versionLabel:
          - app.kubernetes.io/name=argocd-server
    - name: Gitea
      namespace: gitea-system
      selector:
        matchLabels:
          statusLabel:
          - app=gitea
          versionLabel:
          - app=gitea
    - name: Hyperregistry
      namespace: hyperregistry
      selector:
        matchLabels:
          statusLabel:
          - app=harbor
          versionLabel:
          - app=harbor
    - name: Loki
      namespace: monitoring
      selector:
        matchLabels:
          statusLabel:
          - app=loki
          versionLabel:
          - app=loki