{{- if eq .Values.global.hpcdMode "multi" -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    hypercloud: multi-operator
  name: hypercloud-multi-operator-controller-manager
  namespace: hypercloud5-system
spec:
  replicas: 1
  selector:
    matchLabels:
      hypercloud: multi-operator
  template:
    metadata:
      labels:
        hypercloud: multi-operator
    spec:
      containers:
      - args:
        - --metrics-addr=127.0.0.1:8080
        - --enable-leader-election
        - --zap-log-level={{ .Values.multiOperator.logLevel }}
        command:
        - /manager
        env:
        - name: HC_DOMAIN
          value: {{ .Values.global.domain }}
        - name: AUTH_CLIENT_SECRET
          value: {{ .Values.global.hyperAuth.clientSecret }}
        - name: AUTH_SUBDOMAIN
          value: {{ .Values.global.hyperAuth.subDomain }}
        {{- if .Values.global.offline.enabled }}
        image: {{ .Values.global.offline.registry }}/tmaxcloudck/hypercloud-multi-operator:{{ .Values.multiOperator.version }}
        {{- else }}
        image: tmaxcloudck/hypercloud-multi-operator:{{ .Values.multiOperator.version }}
        {{- end }}
        name: manager
        ports:
        - containerPort: 9443
          name: webhook-server
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 20Mi
        volumeMounts:
        - mountPath: /tmp/k8s-webhook-server/serving-certs
          name: cert
          readOnly: true
        - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
          name: hypercloud-multi-operator-controller-manager-token
          readOnly: true
        {{- include "hypercloud.volumeMounts.timeZone" . | nindent 8 }}
      - args:
        - --secure-listen-address=0.0.0.0:8443
        - --upstream=http://127.0.0.1:8080/
        - --logtostderr=true
        - --v=10
        {{- if .Values.global.offline.enabled }}
        image: {{ .Values.global.offline.registry }}/gcr.io/kubebuilder/kube-rbac-proxy:{{ .Values.multiOperator.rbacProxy.version }}
        {{- else }}
        image: gcr.io/kubebuilder/kube-rbac-proxy:{{ .Values.multiOperator.rbacProxy.version }}
        {{- end }}
        name: kube-rbac-proxy
        ports:
        - containerPort: 8443
          name: https
        resources:
          limits:
            cpu: 100m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
        volumeMounts:
        - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
          name: hypercloud-multi-operator-controller-manager-token
          readOnly: true
      serviceAccountName: hypercloud-multi-operator-controller-manager
      terminationGracePeriodSeconds: 10
      volumes:
      - name: cert
        secret:
          defaultMode: 420
          secretName: hypercloud-multi-operator-webhook-server-cert
      - name: hypercloud-multi-operator-controller-manager-token
        secret:
          defaultMode: 420
          secretName: hypercloud-multi-operator-controller-manager-token
      {{- include "hypercloud.volumes.timeZone" . | nindent 6 }}
{{- end -}}