apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana-operator-val-cert
  namespace: monitoring
spec:
  secretName: grafana-webhook
  duration: 2880h0m0s
  dnsNames:
    - grafana-operator-service.monitoring.svc
    - grafana-operator-service.svc.cluster.local    
    - grafana-operator-service  
    - grafana-operator-service.monitoring.svc
    - grafana-operator-service.monitoring.svc.cluster.local    
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - digital signature
    - key encipherment
    - server auth
    - client auth
  issuerRef:
    name: tmaxcloud-issuer
    kind: ClusterIssuer
    group: cert-manager.io