apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: grafana-operator
  name: grafana-operator-service
  namespace: monitoring
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  - name: webhook
    port: 9443
    protocol: TCP
    targetPort: webhook
  selector:
    control-plane: grafana-operator
