apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: grafana-operator-validating-webhook-configuration
  namespace: monitoring
  annotations:
    cert-manager.io/inject-ca-from: monitoring/grafana-operator-val-cert
webhooks:
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    service:
      name: controller-manager-metrics-service
      namespace: monitoring
      path: /validate
      port: 9443
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: controller-manager-metrics-service.monitoring.svc.cluster
  rules:
  - apiGroups:
    - integreatly.org
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - grafanas
