apiVersion: integreatly.org/v1alpha1
kind: GrafanaDataSource
metadata:
  name: grafanadatasource
  namespace: monitoring
spec:
  name: middleware.yaml
  datasources:
    - name: prometheus
      type: prometheus
      access: proxy
      url: http://prometheus-k8s.monitoring.svc.cluster.local:9090
      isDefault: true
      version: 1
      editable: true
      jsonData:
        tlsSkipVerify: true
        timeInterval: "5s"
