## ref. https://developers.redhat.com/articles/2022/04/13/manage-namespaces-multitenant-clusters-argo-cd-kustomize-and-helm#a_simple_argo_cd_application

# Default values for namespace-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
#specifies the quota to be used for resources

namespace: "api-gateway-system"

quota:
  enabled: false
  requests:
    cpu: '1'
    memory: 1Gi
  limits:
    cpu: '2'
    memory: 2Gi
  pods: "10"
  persistentvolumeclaims: "20"
  resourcequotas: "1"
  services: "5"

  #specifies the limit ranges for the chart
limits:
  enabled: false
  default:
    cpu: 200m
    memory: 512Mi
  defaultRequest:
    cpu: 100m
    memory: 256Mi
  type: Container