apiVersion: v1
kind: Secret
metadata:
  name: "{{ template "harbor.registryCtl" . }}"
  namespace: {{ .Values.namespace }}
  labels:
{{ include "harbor.labels" . | indent 4 }}
type: Opaque
data:
  {{- template "harbor.traceJaegerPassword" . }}
