{{ $isMaster := eq .Values.global.cluster "master" }}
{{ if .Values.modules.gitlab.enabled }}
{{ $prefix := printf "%s-%s" .Values.global.clusterNamespace .Values.global.clusterName }}
{{ $module := "gitlab" }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    cluster: {{ ternary "master" $prefix $isMaster }}
  name: {{ ternary $module (printf "%s-%s" $prefix $module) $isMaster }}
  namespace: argocd
spec:
  destination:
    name: {{ .Values.global.clusterName }}
    namespace: gitlab-system
  project: {{ .Values.spec.project }}
  source:
    helm:
      parameters:
        - name: global.registry.is_offline
          value: "{{ .Values.global.network.disabled }}"
        - name: global.registry.private_registry
          value: {{ .Values.global.privateRegistry }}
        - name: ingress.hosts.domain
          value: {{ .Values.global.domain }}
        - name: ingress.hosts.subdomain
          value: {{ .Values.modules.gitlab.subdomain }}
        - name: externalURL
          value: {{ printf "http://%s.%s" .Values.modules.gitlab.subdomain .Values.global.domain }}
        - name: global.timezone
          value: {{ .Values.global.timeZone }}
        - name: pvc.storage
          value: {{ .Values.modules.gitlab.pvc.storage }}
        - name: pvc.storageClassName
          value: {{ .Values.modules.gitlab.pvc.storageClassName }}
        - name: global.logLevel
          value: "{{ .Values.modules.gitlab.logLevel }}"
        ## oidc 
        - name: keycloak.enabled
          value: "{{ .Values.modules.gitlab.oidc.enabled }}"
        - name: keycloak.url
          value: https://{{ include "hyperAuth.domain" . }}
        - name: keycloak.client_secret
          value: {{ include "hyperAuth.tmaxClientSecret" . }}
    path: manifest/gitlab
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
{{ end }}
