{{ if .Values.modules.serviceMesh.istio.enabled }}
{{ $isMaster := eq .Values.global.cluster "master" }}
{{ $prefix := printf "%s-%s" .Values.global.clusterNamespace .Values.global.clusterName }}
{{ $module := "istio" }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    cluster: {{ ternary "master" $prefix $isMaster }}
  name: {{ ternary $module (printf "%s-%s" $prefix $module) $isMaster }}
  namespace: argocd
spec:
  destination:
    name: {{ .Values.global.clusterName }}
    namespace: istio-system
  project: {{ .Values.spec.project }}
  source:
    directory:
      jsonnet:
        tlas:
          - name: is_offline
            value: "{{ .Values.global.network.disabled }}"
          - name: private_registry
            value: {{ .Values.global.privateRegistry }}
          - name: istiod_pilot_discovery_loglevel
            value: {{ .Values.modules.serviceMesh.istio.istiodPilotDiscoveryLoglevel }}
          - name: ingressgateway_pilot_agent_loglevel
            value: {{ .Values.modules.serviceMesh.istio.ingressgatewayPilotAgentLoglevel }}
          - name: istio_proxy_loglevel
            value: {{ .Values.modules.serviceMesh.istio.envoyProxyLoglevel }}
          - name: time_zone
            value: {{ .Values.global.timeZone }}
    path: manifest/service-mesh/istio
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
  syncPolicy: 
    retry: {{ include "argocd.syncPolicy.retry" . | indent 6 }}
{{ end }}