{{ if .Values.modules.serviceMesh.jaeger.enabled }}
{{ $isMaster := eq .Values.global.cluster "master" }}
{{ $prefix := printf "%s-%s" .Values.global.clusterNamespace .Values.global.clusterName }}
{{ $module := "jaeger" }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    cluster: {{ ternary "master" $prefix $isMaster }}
  name: {{ ternary $module (printf "%s-%s" $prefix $module) $isMaster }}
  namespace: argocd
spec:
  destination:
    name: {{ .Values.global.clusterName }}
    namespace: istio-system
  project: {{ .Values.spec.project }}
  source:
    directory:
      jsonnet:
        tlas:
          - name: is_offline
            value: "{{ .Values.global.network.disabled }}"
          - name: private_registry
            value: {{ .Values.global.privateRegistry }}
          - name: tmax_client_secret
            value: {{ include "hyperAuth.tmaxClientSecret" . }}
          - name: HYPERAUTH_DOMAIN
            value: {{ include "hyperAuth.domain" . }}
          - name: CUSTOM_DOMAIN_NAME
            value: {{ .Values.global.domain }}
          - name: jaeger_client_id
            value: {{ ternary $module (printf "%s-%s" $prefix $module) $isMaster }}
          - name: jaeger_subdomain
            value: {{ .Values.modules.serviceMesh.jaeger.subdomain }}
          - name: jaeger_collector_log_level
            value: {{ .Values.modules.serviceMesh.jaeger.jaegerCollectorLoglevel }}
          - name: jaeger_agent_log_level
            value: {{ .Values.modules.serviceMesh.jaeger.jaegerAgentLoglevel }}
          - name: jaeger_query_log_level
            value: {{ .Values.modules.serviceMesh.jaeger.jaegerQueryLoglevel }}
          - name: gatekeeper_log_level
            value: {{ .Values.modules.serviceMesh.jaeger.gatekeeperLoglevel }}
          - name: time_zone
            value: {{ .Values.global.timeZone }}
    path: manifest/service-mesh/jaeger
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
{{ end }}