{{ if .Values.modules.serviceMesh.kiali.enabled }}
{{ $isMaster := eq .Values.global.cluster "master" }}
{{ $prefix := printf "%s-%s" .Values.global.clusterNamespace .Values.global.clusterName }}
{{ $module := "kiali" }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    cluster: {{ ternary "master" $prefix $isMaster }}
  name: {{ ternary $module (printf "%s-%s" $prefix $module) $isMaster }}
  namespace: argocd
spec:
  destination:
    name: {{ .Values.global.clusterName }}
    namespace: istio-system
  project: {{ .Values.spec.project }}
  source:
    directory:
      jsonnet:
        tlas:
          - name: is_offline
            value: "{{ .Values.global.network.disabled }}"
          - name: private_registry
            value: {{ .Values.global.privateRegistry }}
          - name: HYPERAUTH_DOMAIN
            value: {{ .Values.global.keycloak.domain }}
          - name: CUSTOM_DOMAIN_NAME
            value: {{ .Values.global.domain }}
          - name: kiali_subdomain
            value: {{ .Values.modules.serviceMesh.kiali.subdomain }}
          - name: client_id
            value: {{ ternary $module (printf "%s-%s" $prefix $module) $isMaster }}
    path: manifest/service-mesh/kiali
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
{{ end }}