{{- if .Values.modules.nfs.enabled }}
{{ $isMaster := eq .Values.global.cluster "master" }}
{{ $prefix := printf "%s-%s" .Values.global.clusterNamespace .Values.global.clusterName }}
{{ $module := "nfs" }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    cluster: {{ ternary "master" $prefix $isMaster }}
  name: {{ ternary $module (printf "%s-%s" $prefix $module) $isMaster }}
  namespace: argocd
spec:
  destination:
    name: {{ .Values.global.clusterName }}
    namespace: nfs
  project: {{ .Values.spec.project }}
  source:
    helm:
      parameters:
        - name: nfs.server
          value: {{ .Values.modules.nfs.server }}
        - name: nfs.path
          value: {{ .Values.modules.nfs.path }}
        {{- if eq .Values.modules.nfs.defaultClass "default" }}
        - name: storageClass.defaultClass
          value: "true"
          forceString: true
        {{- end }}
        - name: timeZone
          value: {{ .Values.global.timeZone }}
        {{- if ne (.Values.modules.nfs.logLevel | toString) "0" }}
        - name: logtostderr
          value: "true"
          forceString: true
        - name: logLevel
          value: "{{ sub .Values.modules.nfs.logLevel 1 }}"
          forceString: true
        {{- end }}
        {{- if .Values.global.network.disabled }}
        - name: image.repository
          value: "{{ .Values.global.privateRegistry }}/nfs-subdir-external-provisioner"
        {{- end }}
    path: manifest/nfs-subdir-external-provisioner
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
{{- end }}