apiVersion: servicecatalog.k8s.io/v1beta1
kind: ClusterServiceBroker
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: cluster-tsb
spec:
  url: http://cluster-template-service-broker.cluster-tsb-ns.svc.cluster.local:80

---
apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceBroker
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: tsb
  namespace: tsb-ns
spec:
  url: http://template-service-broker.tsb-ns.svc.cluster.local:80