apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: hyperauth-kafka-jks-certificate
  namespace: hyperauth
spec:
  secretName: hyperauth-kafka-jks
  commonName: hyperauth
  keySize: 2048
  duration: 8760h0m0s # 360d=1y
  renewBefore: 720h0m0s # 30d
  keyAlgorithm: rsa
  keyEncoding: pkcs1
  keystores:
    jks:
      create: true
      passwordSecretRef: # Password used to encrypt the keystore
        key: CERTS_PASSWORD
        name: passwords
  usages:
    - digital signature
    - key encipherment
    - server auth
  issuerRef:
    name: tmaxcloud-issuer
    kind: ClusterIssuer
    group: cert-manager.io
    
---

apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: kafka-broker-jks-certificate
  namespace: hyperauth
spec:
  secretName: kafka-jks
  commonName: kafka
  dnsNames:
    - kafka-kafka-bootstrap.hyperauth
    - "*.kafka-kafka-brokers.hyperauth.svc"
    - "*.hyperauth"
    - tmax-cloud
  keySize: 2048
  duration: 8760h0m0s # 360d=1y
  renewBefore: 720h0m0s # 30d
  keyAlgorithm: rsa
  keyEncoding: pkcs1
  keystores:
    jks:
      create: true
      passwordSecretRef: # Password used to encrypt the keystore
        key: CERTS_PASSWORD
        name: passwords
  usages:
    - digital signature
    - key encipherment
    - server auth
  issuerRef:
    name: tmaxcloud-issuer
    kind: ClusterIssuer
    group: cert-manager.io
