{{- if .Values.chartmuseum.enabled }}
{{- $persistence := .Values.persistence -}}
{{- if $persistence.enabled }}
{{- $chartmuseum := $persistence.persistentVolumeClaim.chartmuseum -}}
{{- if and (not $chartmuseum.existingClaim) (eq $persistence.imageChartStorage.type "filesystem") }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "harbor.chartmuseum" . }}
  namespace: {{ .Values.namespace }}
  annotations:
  {{- range $key, $value := $chartmuseum.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- if eq .Values.persistence.resourcePolicy "keep" }}
    helm.sh/resource-policy: keep
  {{- end }}
  labels:
{{ include "harbor.labels" . | indent 4 }}
    component: chartmuseum
spec:
  accessModes: 
    - {{ $chartmuseum.accessMode }}
  resources:
    requests:
      storage: {{ $chartmuseum.size }}
  {{- if .Values.storageClass }}
    {{- if eq "-" .Values.storageClass }}
  storageClassName: ""
    {{- else }}
  storageClassName: {{ .Values.storageClass }}
    {{- end }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}