{
 "title": "hyperauth Metrics",
 "description": "Monitoring keycloak metrics",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(hyperauth_users,instance)"
   },
   {
    "name": "realm",
    "label": "Realm",
    "query": "label_values(hyperauth_users{instance=\"$instance\"},realm)"
   },
   {
    "name": "ClientId",
    "label": "ClientId",
    "query": "label_values(hyperauth_logins{instance=\"$instance\",realm=\"$realm\"},client_id)"
   }
  ]
 },
 "panels": [
  {
   "title": "Hyperauth Users per Realm",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (realm)(hyperauth_users)",
     "legendFormat": "{{realm}}"
    }
   ]
  },
  {
   "title": "User Sessions per Realm",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 7, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "avg by (realm)(hyperauth_user_sessions)",
     "legendFormat": "{{realm}}"
    }
   ]
  },
  {
   "title": "User Sessions per Realm - Client_id",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "avg by (realm,client_id)(hyperauth_user_sessions)",
     "legendFormat": "{{realm}} - {{client_id}}"
    }
   ]
  },
  {
   "title": "Email Send Request per Realm - Mail server",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (realm,mailServer)(increase(hyperauth_mail_request[1h]))",
     "legendFormat": "{{realm}} - {{mailServer}}"
    }
   ]
  },
  {
   "title": "Email Send per Realm - Mail server",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 9, "y": 8 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (realm, mailServer)(increase(hyperauth_mail_send[1h]))",
     "legendFormat": "{{realm}} - {{mailServer}}"
    }
   ]
  },
  {
   "title": "Email Send Failed per Realm - Mail server",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 8 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (realm, mailServer)(increase(hyperauth_failed_mail_send[1h]))",
     "legendFormat": "{{realm}} - {{mailServer}}"
    }
   ]
  },
  {
   "title": "Current Memory HEAP",
   "type": "singlestat",
   "description": "Memory currently being used by Keycloak.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 15 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(jvm_memory_bytes_used{instance=\"$instance\", area=\"heap\"})*100/sum(jvm_memory_bytes_max{instance=\"$instance\", area=\"heap\"})\n"
    }
   ]
  },
  {
   "title": "Current Memory nonHEAP",
   "type": "singlestat",
   "description": "Memory currently being used by Keycloak.",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 15 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(jvm_memory_bytes_used{instance=\"$instance\", area=\"nonheap\"})*100/sum(jvm_memory_bytes_max{instance=\"$instance\", area=\"nonheap\"})"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_bytes_max{instance=\"$instance\",job=\"hyperauth\"})",
     "legendFormat": "Max"
    },
    {
     "expr": "sum(jvm_memory_bytes_committed{instance=\"$instance\",job=\"hyperauth\"})",
     "legendFormat": "Comitted"
    },
    {
     "expr": "sum(jvm_memory_bytes_used{instance=\"$instance\",job=\"hyperauth\"})",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "Login Attempts per Client on Tmax Realm",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (client_id) (increase(hyperauth_login_attempts{realm=\"tmax\",job=\"hyperauth\"}[1h]))",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  {
   "title": "Logins per Realm",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (realm)(increase(hyperauth_logins[1h]))",
     "legendFormat": "{{realm}}"
    }
   ]
  },
  {
   "title": "Login Errors on Tmax Realm",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (error)(increase(hyperauth_failed_login_attempts{realm=\"tmax\",job=\"hyperauth\"}[1h]))",
     "legendFormat": "{{error}}"
    }
   ]
  },
  {
   "title": "Login per Client on Tmax Realm",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (client_id)(increase(hyperauth_logins{realm=\"tmax\",job=\"hyperauth\"}[1h]))",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  {
   "title": "Registrations per Realm - Client_id",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (client_id, realm) (hyperauth_registrations{job=\"hyperauth\"})",
     "legendFormat": "{{realm}} - {{client_id}}"
    }
   ]
  },
  {
   "title": "Registration Errors per Realm - Client_id",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (client_id, realm) (hyperauth_registrations_errors{job=\"hyperauth\"})",
     "legendFormat": "{{realm}} - {{client_id}}"
    }
   ]
  }
 ]
}