apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: "{{ template "harbor.rbac.role" . }}"
  namespace: {{ .Values.namespace }}
  labels:
{{ include "harbor.labels" . | indent 4 }}
rules:
- apiGroups: [""]
  resources: [""]
  verbs: [""]
