{{- if eq .Values.redis.type "internal" -}}
{{- $redis := .Values.persistence.persistentVolumeClaim.redis -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "harbor.redis" . }}
  namespace: {{ .Values.namespace }}
  labels:
{{ include "harbor.labels" . | indent 4 }}
    component: redis
spec:
  replicas: 1
  serviceName: {{ template "harbor.redis" . }}
  selector:
    matchLabels:
{{ include "harbor.matchLabels" . | indent 6 }}
      component: redis
  template:
    metadata:
      labels:
{{ include "harbor.labels" . | indent 8 }}
        component: redis
{{- if .Values.redis.podAnnotations }}
      annotations:
{{ toYaml .Values.redis.podAnnotations | indent 8 }}
{{- end }}
    spec:
      securityContext:
        runAsUser: 999
        fsGroup: 999
{{- if .Values.redis.internal.serviceAccountName }}
      serviceAccountName: {{ .Values.redis.internal.serviceAccountName }}
{{- else }}
      serviceAccountName: {{ include "harbor.rbac.serviceAccount" . }}
{{- end -}}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      automountServiceAccountToken: {{ .Values.redis.internal.automountServiceAccountToken | default false }}
      terminationGracePeriodSeconds: 120
      containers:
      - name: redis
        {{- if .Values.global.registry.is_offline }}
        image: {{ .Values.global.registry.private_registry }}/{{ .Values.redis.internal.image.repository }}:{{ .Values.redis.internal.image.tag }}
        {{- else }}
        image: {{ .Values.redis.internal.image.repository }}:{{ .Values.redis.internal.image.tag }}
        {{- end }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        livenessProbe:
          tcpSocket:
            port: 6379
          initialDelaySeconds: 300
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: 6379
          initialDelaySeconds: 1
          periodSeconds: 10
{{- if .Values.redis.internal.resources }}
        resources:
{{ toYaml .Values.redis.internal.resources | indent 10 }}
{{- end }}
        volumeMounts:
        {{- if ne .Values.global.time_zone "UTC" }}
        - name: timezone-config
          mountPath: /etc/localtime
        {{- end }}
        - name: data
          mountPath: /var/lib/redis
          subPath: {{ $redis.subPath }}
        - name: redis-config
          mountPath: /etc/redis.conf
          subPath: redis.conf
      volumes:
      - name: redis-config
        configMap:
          name: "{{ template "harbor.redis" . }}"
      {{- if ne .Values.global.time_zone "UTC" }}
      - name: timezone-config
        hostPath: 
          path: {{ printf "%s%s" "/usr/share/zoneinfo/" .Values.global.time_zone }}
      {{- end }}
      {{- if not .Values.persistence.enabled }}
      - name: data
        emptyDir: {}
      {{- else if $redis.existingClaim }}
      - name: data
        persistentVolumeClaim:
          claimName: {{ $redis.existingClaim }}
      {{- end -}}
    {{- with .Values.redis.internal.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.redis.internal.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.redis.internal.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- if .Values.redis.internal.priorityClassName }}
      priorityClassName: {{ .Values.redis.internal.priorityClassName }}
    {{- end }}
  {{- if and .Values.persistence.enabled (not $redis.existingClaim) }}
  volumeClaimTemplates:
  - metadata:
      name: data
      labels:
{{ include "harbor.labels" . | indent 8 }}
      annotations:
      {{- range $key, $value := $redis.annotations }}
        {{ $key }}: {{ $value | quote }}
      {{- end }}
    spec:
      accessModes: [{{ $redis.accessMode | quote }}]
      {{- if .Values.storageClass }}
      {{- if eq "-" .Values.storageClass }}
      storageClassName: ""
      {{- else }}
      storageClassName: "{{ .Values.storageClass }}"
      {{- end }}
      {{- end }}
      resources:
        requests:
          storage: {{ $redis.size | quote }}
  {{- end -}}
  {{- end -}}
