apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cicd-operator
  namespace: argocd
spec:
  destination:
    namespace: cicd-system
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      jsonnet:
        tlas:
          - name: is_offline
            value: "false"
          - name: private_registry
            value: registry.tmaxcloud.org
          - name: custom_domain
            value: tmaxcloud.org
    path: manifest/cicd-operator
    repoURL: https://github.com/tmax-cloud/argocd-installer
    targetRevision: main