apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: strimzi-kafka-cluster-operator
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: kafka
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    directory:
      jsonnet:
        tlas:
          - name: is_offline
            value: "false"
          - name: private_registry
            value: 172.22.6.2:5000
    path: manifest/strimzi-kafka-cluster-operator
    repoURL: 'https://github.com/tmax-cloud/argocd-installer'
    targetRevision: main

